[package]
name = "raz"
version = "0.1.0"
authors = ["Andriy Symonovych on lilac <sima.rv@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6"
termion = "1"

